name: Testing

on: [push, pull_request, workflow_dispatch]

jobs:
  testing:
    name: Miniconda ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/my_actions/conda-setup
        with:
          env_name: gpiowrapper
          env_file_path: testing_environment.yml
          python_version: 3.11

      - name: Print Conda Information
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest --junitxml=junit/test-results-${{ matrix.os }}-py${{ matrix.python-version }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.os }}-py${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
